### ISSUE TITLE
关于insert语句的语法好像有点问题

### ISSUE THREAD

**Issue by caiji-programer** [ascoders/syntax-parser#10]
在 src/demo/sql-parser/mysql/parser.ts 中，博主的的语法是这样的: 
` chain('insert', optional('ignore'), 'into', tableName, optional(selectFieldsInfo),[selectStatement])`
这好像与mysql的语法：
`INSERT INTO table_name (column1,column2,column3,...) VALUES (value1,value2,value3,...)`
不太符合。
博主有时间麻烦修改一下，或者看看我发起的这个Pull request #https://github.com/ascoders/syntax-parser/pull/9 ，请指教。

**Comment by ascoders** [comment]
这个没关系，是 Demo 代码，具体用的时候再定制好了。
