### ISSUE TITLE
能导出一下 d.ts 声明文件吗？

### ISSUE THREAD

**Issue by whinc** [ascoders/syntax-parser#11]
在 TS 项目中使用时没有类型提示。

**Comment by muzea** [comment]
其实  [有 types 字段](https://unpkg.com/browse/syntax-parser@1.0.15/package.json)，[类型文件也在](https://unpkg.com/browse/syntax-parser@1.0.15/declaration/src/index.d.ts)，只是这里 `types` 的路径有点问题，少了一个 `src` 吧。

这个锅应该是 `pri` 来背？

**Comment by muzea** [comment]
有个问题比较奇怪，为啥 `src` 里面的文件叫 `index.tsx` ？ :doge:

**Comment by whinc** [comment]
明白了，这个是 pri 修复？还是提个PR修正下路径？

**Comment by neostfox** [comment]
> 

pri 在win上跑不起来，直接提了一个pr修正路径。

**Comment by ascoders** [comment]
pr 已合，其实源码也不多，可以考虑把源码拷贝到自己项目里，完全不依赖三方库。

**Comment by neostfox** [comment]
@ascoders  主要是这个问题有时候不查一下还是点困惑的，造轮子，咱们也别让人拿到轮子还得补胎不是？感谢合并pr

**Comment by neostfox** [comment]
我认为这个issue可以关闭了。

**Comment by IQZoe** [comment]
> pr 已合，其实源码也不多，可以考虑把源码拷贝到自己项目里，完全不依赖三方库。

我试过copy源码，但是发现源码的ts一堆问题，之前开源的时候都没问题么

**Comment by IQZoe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
