### ISSUE TITLE
Npm scripts 脚本缺失了docs脚本

### ISSUE THREAD

**Issue by mumiao** [ascoders/syntax-parser#19]
执行`pnpm docs`,link 到 https://www.npmjs.com/package/syntax-parser 这个地方了。没有`debugger`编辑器界面

**Comment by kuiniela** [comment]
碰到同样问题

**Comment by mumiao** [comment]
`pnpm start`脚本运行也有问题

**Comment by kuiniela** [comment]
> > 碰到相同问题
> 
> 当前`pri`这个脚手架也没有在devDependies里面，需要`npx pri`去下载，下载完成去执行`start`还会有问题
是的，执行npm run start时候，我碰到了这个问题
`\node_modules\.bin\pri:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1106:15)
    at Module._compile (internal/modules/cjs/loader.js:1140:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1`
我还尝试了发布的1.0.15版本，其中有docs脚本，但是也会提示，并且找不到错误原因
`npm ERR! code ELIFECYCLE
npm ERR! errno 1`
心累

**Comment by kuiniela** [comment]
我用linux运行成功了，用的是最新版本

**Comment by mumiao** [comment]
> > 当前`pri`这个脚手架也没有在devDependies里面，需要`npx pri`去下载，下载完成去执行`start`还会有问题
> 
> 是的，执行npm run start时候，我碰到了这个问题 `\node_modules.bin\pri:2 basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')") ^^^^^^^
> 
> SyntaxError: missing ) after argument list at Object.compileFunction (vm.js:344:18) at wrapSafe (internal/modules/cjs/loader.js:1106:15) at Module._compile (internal/modules/cjs/loader.js:1140:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10) at Module.load (internal/modules/cjs/loader.js:1040:32) at Function.Module._load (internal/modules/cjs/loader.js:929:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) at internal/main/run_main_module.js:17:47 npm ERR! code ELIFECYCLE npm ERR! errno 1`
> 
> 我还尝试了发布的1.0.15版本，其中有docs脚本，但是也会提示，并找不到错误原因
> 
> `npm ERR! code ELIFECYCLE npm ERR! errno 1`
> 
> 心累

我也是，目前我通过vscode 去 debugger test脚本的

**Comment by mumiao** [comment]
@ascoders cc.  目前最新的分支构建问题挺多的

**Comment by kuiniela** [comment]
我用linux跑通了，现在又碰到了虚拟机localhost:8000无法在win上打开的问题，关闭防火墙等方法都不行，翻阅博客得知可能要指定localhost为虚拟机ip，但pri作为作者的另一个项目，没有指定host的配置

**Comment by kuiniela** [comment]
> > > 当前`pri`这个脚手架也没有在devDependies里面，需要`npx pri`去下载，下载完成去执行`start`还会有问题
> > 
> > 
> > 是的，执行npm run start时候，我碰到了这个问题 `\node_modules.bin\pri:2 basedir=$(dirname "$(echo "$0" | sed -e 's,,/,g')") ^^^^^^^
> > SyntaxError: missing ) after argument list at Object.compileFunction (vm.js:344:18) at wrapSafe (internal/modules/cjs/loader.js:1106:15) at Module._compile (internal/modules/cjs/loader.js:1140:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10) at Module.load (internal/modules/cjs/loader.js:1040:32) at Function.Module._load (internal/modules/cjs/loader.js:929:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) at internal/main/run_main_module.js:17:47 npm ERR! code ELIFECYCLE npm ERR! errno 1`
> > 我还尝试了发布的1.0.15版本，其中有docs脚本，但是也会提示，并找不到错误原因
> > `npm ERR! code ELIFECYCLE npm ERR! errno 1`
> > 心累
> 
> 我也是，目前我通过vscode 去 debugger test脚本的

听说是windows的shell不支持这种路径读取，我换了linux跑通了，但碰到虚拟机起了一个localhost:8000，但是win无法通过虚拟机IP:8000方式访问的问题，博客提到可能是需要指定localhost为虚拟机ip，但是pri作为作者的另一个项目，无法指定host，也无法指定webpack配置

**Comment by kuiniela** [comment]
https://www.cnblogs.com/dontes/p/9230196.html

**Comment by kuiniela** [comment]
demo之类的文件夹不删除跳unexpected files错误，删了吧轮到basic.tsx和monaco-editor.tsx说找不到demo，真是好家伙

**Comment by mumiao** [comment]
> > > > 当前`pri`这个脚手架也没有在devDependies里面，需要`npx pri`去下载，下载完成去执行`start`还会有问题
> > > 
> > > 
> > > 是的，执行npm run start时候，我碰到了这个问题 `\node_modules.bin\pri:2 basedir=$(dirname "$(echo "$0" | sed -e 's,,/,g')") ^^^^^^^ SyntaxError: missing ) after argument list at Object.compileFunction (vm.js:344:18) at wrapSafe (internal/modules/cjs/loader.js:1106:15) at Module._compile (internal/modules/cjs/loader.js:1140:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10) at Module.load (internal/modules/cjs/loader.js:1040:32) at Function.Module._load (internal/modules/cjs/loader.js:929:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) at internal/main/run_main_module.js:17:47 npm ERR! code ELIFECYCLE npm ERR! errno 1`
> > > 我还尝试了发布的1.0.15版本，其中有docs脚本，但是也会提示，并找不到错误原因
> > > `npm ERR! code ELIFECYCLE npm ERR! errno 1`
> > > 心累
> > 
> > 
> > 我也是，目前我通过vscode 去 debugger test脚本的
> 
> 听说是windows的shell不支持这种路径读取，我换了linux跑通了，但碰到虚拟机起了一个localhost:8000，但是win无法通过虚拟机IP:8000方式访问的问题，博客提到可能是需要指定localhost为虚拟机ip，但是pri作为作者的另一个项目，无法指定host，也无法指定webpack配置

我是用linux的，还是报这个错

**Comment by Mrsure0324** [comment]
> > > > > 当前`pri`这个脚手架也没有在devDependies里面，需要`npx pri`去下载，下载完成去执行`start`还会有问题
> > > > 
> > > > 
> > > > 是的，执行npm run start时候，我碰到了这个问题 `\node_modules.bin\pri:2 basedir=$(dirname "$(echo "$0" | sed -e 's,,/,g')") ^^^^^^^ SyntaxError: missing ) after argument list at Object.compileFunction (vm.js:344:18) at wrapSafe (internal/modules/cjs/loader.js:1106:15) at Module._compile (internal/modules/cjs/loader.js:1140:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10) at Module.load (internal/modules/cjs/loader.js:1040:32) at Function.Module._load (internal/modules/cjs/loader.js:929:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) at internal/main/run_main_module.js:17:47 npm ERR! code ELIFECYCLE npm ERR! errno 1`
> > > > 我还尝试了发布的1.0.15版本，其中有docs脚本，但是也会提示，并找不到错误原因
> > > > `npm ERR! code ELIFECYCLE npm ERR! errno 1`
> > > > 心累
> > > 
> > > 
> > > 我也是，目前我通过vscode 去 debugger test脚本的
> > 
> > 
> > 听说是windows的shell不支持这种路径读取，我换了linux跑通了，但碰到虚拟机起了一个localhost:8000，但是win无法通过虚拟机IP:8000方式访问的问题，博客提到可能是需要指定localhost为虚拟机ip，但是pri作为作者的另一个项目，无法指定host，也无法指定webpack配置
> 
> 我是用linux的，还是报这个错

请问这个看您关闭了，是解决了么，我也遇到这个错误
