### ISSUE TITLE
【咨询】关于sql智能提示相关的实践

### ISSUE THREAD

**Issue by ayo4code** [ascoders/syntax-parser#4]
最近在研究web版sql编辑器相关的东西，看到你好像做过很多相关的东西。想问下

1.  能否交流下相关实践，比如语法解析，语法、库表名提示，错误解析（可能和语法解析是提个东西~~）
2. 有兴趣基于这个库写个sql智能提示的demo吗？只看文档上的demo还是不太明白怎么用你这个库怎么用
3. 求加wx

**Comment by ascoders** [comment]
![image](https://user-images.githubusercontent.com/7970947/59973516-898f0380-95d3-11e9-9beb-4aa24763800b.png)

Clone 本仓库，执行 `npm run docs` 即可看到我新增的 sql 编辑器 demo

**Comment by ascoders** [comment]
![image](https://user-images.githubusercontent.com/7970947/59973607-97915400-95d4-11e9-8c91-8a2c48a4173d.png)

Demo 里的两个文件夹，分别是基于 syntax-parser 拓展的 sql-parser，以及基于 sql-parser 拓展的 monaco-sql-plugin，demo 调用 monaco-sql-plugin 就出现如图的效果了

**Comment by ayo4code** [comment]
好的，十分感谢
